### ISSUE TITLE
Add Html Tag in Hint attribute

### ISSUE THREAD

**Issue by Amit1150** [chinchang/hint.css#108]
I have added Html tag in <b>data-hint</b> attribute. But In tooltip It shows html tag too. 

I have also set <b>data-html="true"</b>. But It's not working.

[See here Fiddle linjk](https://jsfiddle.net/Amit12x/n5m3tejj/4/)

**Comment by chinchang** [comment]
Hint.css doesn't support HTML inside the tooltips.

**Comment by et** [comment]
@chinchang - Being able to represent HTML entities would be nice for usage with FontAwesome. e.g. I want to display an [exclamation-circle](http://fortawesome.github.io/Font-Awesome/icon/exclamation-circle/) before the text in the data attribute.

**Comment by chinchang** [comment]
@et Its a limitation of pseudo element's `content` property (which hint.css uses) that it doesn't support HTML inside it yet.

**Comment by et** [comment]
Yeah it's a bummer that we don't have multiple content properties (apparently this was suggested for CSS3 but knocked down).

I think it would be required to have some kind of multiple block elements. What are your thoughts about the following markup?

```html
<span class="hint--bottom" data-hint="foo">
  <span class="hint--before"><i class="fa fa-exclamation-circle"></i></span>
  Hover over me
</span>
```

**Comment by chinchang** [comment]
whats the intended result with the mentioned markup?

**Comment by et** [comment]
@chinchang - roughly this:
<img width="108" alt="screen shot 2016-02-23 at 12 12 38 pm" src="https://cloud.githubusercontent.com/assets/58678/13263431/c77d350c-da26-11e5-97b8-feca974cb855.png">
