### ISSUE TITLE
Using white-space: pre / pre-wrap break the arrows on Firefox

### ISSUE THREAD

**Issue by petetnt** [chinchang/hint.css#120]
Ran into this browser quirk today: using `white-space: pre` or `white-space: pre-wrap` on any of the parent elements to the tooltip or the tooltip element itself results in the arrow breaking in Firefox:

![image](https://cloud.githubusercontent.com/assets/7641760/12882670/df490b10-ce5b-11e5-9b32-8c915527a963.png)

Works correctly on IE11, Chrome 48, broken in Firefox 42-44 (at least)

**Comment by chinchang** [comment]
Not reproducable any more on Firefox.
