### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by fmsutton** [chinchang/hint.css#129]
Not an issue this is a question.  

I am fairly new to this kind of stuff.  What I am trying to figure out is how to code attributes for hint.css.

for instance <span class="hint--top-left" data-hint="put something here"> if I wanted to make it top-left and alert how do i combine the two attributes?   I have tried combining them several different ways and all it does is default to right.

I appreciate your help.

**Comment by chinchang** [comment]
To show a warning (alert) tooltip top left, you would have to use 2 classes: `hint--top-left` and `hint--warning`.

Example:

`<a class="hint--top-left  hint--warning">Link</a>`
