### ISSUE TITLE
can't work with font-awesome ?

### ISSUE THREAD

**Issue by iyaozhen** [chinchang/hint.css#144]
My code:
```
<i aria-label="camera" class="fa fa-camera-retro fa-lg hint--top"></i>
<br>
<i aria-label="ok" class="hint--bottom">hover</i>
```
`fa-camera` hidden:
![image](https://cloud.githubusercontent.com/assets/4395553/15850472/b26de368-2cca-11e6-8e2f-2d2ab019f827.png)

https://jsfiddle.net/u1ta0hf1/1/

2.3.1/hint.min.css
4.6.3/css/font-awesome.min.css

I think it is a commonly scenes, can suppose it ?

**Comment by lenemson** [comment]
Seems it don't work if you put hint css attribute directly on the font-awesome tag (<i/>) but it works if a span tag wrap it
`<span aria-label="ok" class="hint--bottom">
<i class="fa fa-camera-retro fa-lg"></i>
</span>`

**Comment by chinchang** [comment]
@iyaozhen Font-awesome creates icon using after/before pseudo elements. Hint.css also used after/before pseudo elements to create tooltips. So there is a conflict here and hence tooltips won't show directly on font-awesome icons.

As @lenemson mentioned, you'll have to wrap the icons in some other tag and put tooltips on that instead.

**Comment by iyaozhen** [comment]
@chinchang @lenemson Thank you very much.
