### ISSUE TITLE
Not working in Chrome Canary

### ISSUE THREAD

**Issue by realjoker** [chinchang/hint.css#146]
For some reason, the tooltip is not working in Chrome Canary, even [your examples](http://kushagragour.in/lab/hint/).

Edit: in the page I have linked, the only example working is the one on the download button...

**Comment by chinchang** [comment]
Just checked, seems like Chrome Canary(54.0.2787.0) is completely broken at the moment! There are multiple CSS properties which are not working right now. I recommend not trying out Hint.css on canary.

**Comment by realjoker** [comment]
OK, good to know, thanks

2016-07-04 21:34 GMT+02:00 Kushagra Gour <notifications@github.com>:
