### ISSUE TITLE
the hint won't show up on images !

### ISSUE THREAD

**Issue by stoufa** [chinchang/hint.css#148]
I've tried both data-hint="text" and aria-label="text" !
It works when I wrap the image with a <span> tag but I don't want to do this ! I want to use the <img> tag directly :)

**Comment by chinchang** [comment]
@stoufa Hint.css (or any tooltip library which is CSS only) works with pseudo elements (:after & :before). And images cannot have pseudo elements unfortunately. This is the reason why tooltips don't work directly on tags like image & input.
As you mentioned, wrapping the image in some other tag is the solution.

**Comment by stoufa** [comment]
Ok, Thanks :)
