### ISSUE TITLE
Clarifications about License

### ISSUE THREAD

**Issue by maxweldsouza** [chinchang/hint.css#153]
I was just about to contact you to add [WikiMentions.com](https://wikimentions.com) to the list of projects that use hint.css. But to my surprise I see that the license has switched from MIT. Hint.css is now licensed under AGPL but only for non-commercial purposes. To use it for a commercial purpose I would have to pay $15.

In these conditions is it fair to call it "free and open source"?
[https://opensource.org/faq#commercial](https://opensource.org/faq#commercial)

I hope that you switch back to the MIT License. I really like your library. But with this change, I and probably many others might have to look for something else. Also someone might just create a fork from version 2.3.2 which is MIT Licensed. I don't see any difference between 2.3.2 and 2.4 in the css code. So I don't see the point of all this. Mere sawalon ka.... Jawab do....

**Comment by Calinou** [comment]
> In these conditions is it fair to call it "free and open source"?

Yes, because the AGPLv3 grants you the [four freedoms](https://www.gnu.org/philosophy/free-sw.html), which includes commercial usage. *However*, you have to distribute derivative works under the same license, which is totally fair considering how much you paid for it.

The "commercial" license (which is really a "proprietary-friendly" license) lifts those restrictions.

I suggest you [read the AGPLv3](https://www.gnu.org/licenses/agpl.html) to understand it, it probably takes like 20 minutes to read and understand for most people. Note that the Affero clause, that is, the clause that requires you to distribute the source code of software accessed through a network, will probably not apply to hint.css since CSS is run entirely client-side.

**Comment by chinchang** [comment]
Hey @maxweldsouza, thanks for asking this. And @Calinou for answering it :)

**Is Hint.css opensource?** - Absolutely yes, the source is open just like before for everyone to read and learn from.

**Is Hint.css free** - For personal projects it still is. For projects which are making you money, Hint.css now requires you to purchases a license for it. So basically, if you make money yourself, you need to buy this. I don't see anything wrong here.

As far as creating a fork from 2.3.2 is concerned, sure anyone can do that and its upto them. 2.4.0 (paid) might now be different from 2.3.2 (free), but I never said 2.4.0 is the last version. There would be many more features and fixes coming up with time. If someone is happy with using old versions of the library and not caring about future changes, its all good 👍 .

Happy to answer any more questions you have.

**Comment by johdah** [comment]
@chinchang So the way the license should be parsed is that AGPLv3-projects can't be used unmodified as a library in a larger project? Then I guess I will have to look for a replacement for this library. A sad development then because I liked this project.

**Comment by sihil** [comment]
That's not how I read the license. From what I can tell from having read around the subject ([this](https://softwareengineering.stackexchange.com/questions/107883/agpl-what-you-can-do-and-what-you-cant) seems particularly helpful) provided you only depend on it as an external library (perhaps using npm and a build tool so it's not in your own repo) then you are entirely able to use it for commercial purposes within the license. It's only when you are pulling it into your own source code or modifying the library that you'd need to shift to the commercial license.

Anyhow, life is too short so I'm picking up the react-tooltip library in this instance to be on the safe side, just thought I'd leave these thoughts here for people that come after me.

**Comment by damianb** [comment]
As a note, it's good practice to consider such a license change a breaking change, requiring a new major version under semver, since it's *not* backwards compatible in a legal sense.
