### ISSUE TITLE
How to inactivate hints ?

### ISSUE THREAD

**Issue by fchampreux** [chinchang/hint.css#156]
Great tool !
I'd like to use it for teaching new features of a web product. But hints should be inactivated when user is confident, or reactivated for helping purpose.
How is it possible to activate/inactivate hint ?

Thanks a lot,

Fred

**Comment by chinchang** [comment]
@fchampreux Do you want to disable all hints on the page together or individual ones?

**Comment by fchampreux** [comment]
Actually, I would like to disable all hints at once. 
Thanks a lot,

Fred

**Comment by chinchang** [comment]
You can do the following:

Add following CSS on your page:

```
.hint-disabled [class*="hint--"]:after, .hint-disabled [class*="hint--"]:before {
 display: none;
}
```

Now you can simply toggle the `hint-disabled` class on `body` to enable/disable tooltips.
