### ISSUE TITLE
Updateing Licensing information in the library

### ISSUE THREAD

**Issue by melanholly** [chinchang/hint.css#161]
Hi there A few days ago I discoved hint.css and stared using it for my company project. First in the source files [here](https://github.com/chinchang/hint.css/blob/master/src/hint.scss#L16) and [here](https://github.com/chinchang/hint.css/blob/master/src/hint.base.scss#L17) and in all the files in the `src` forlder they say:
```
/**
 * HINT.css is a tooltip library made in pure CSS.
 *
 * Source: https://github.com/chinchang/hint.css
 * Demo: http://kushagragour.in/lab/hint/
 *
 * Release under The MIT License
 *
 */
```
Please update your licensing information in the soruce files because I have found it early today but someone that have a lot of dependencies for their project might find it too late. 

Edit: I see that in issue #153 it is clarifyed about the license but please update you files.

**Comment by chinchang** [comment]
Ahh. Missed there. Thanks for pointing. Will fix.
