### ISSUE TITLE
No shadow

### ISSUE THREAD

**Issue by edencorbin** [chinchang/hint.css#162]
Is there an option to remove the shadow? Seems like that would be a very common requirement in material/minimal designs.

**Comment by chinchang** [comment]
@edencorbin Valid point. I'll take this up for next release. You are welcome to contribute too :)

**Comment by chinchang** [comment]
FYI, you can use hint-base.css to get simple clean tooltips with no effects.

**Comment by chinchang** [comment]
this is live in v2.6.0. Thanks to @flawimc for taking this up! 👍
