### ISSUE TITLE
How do I automatically match the position?

### ISSUE THREAD

**Issue by wilon** [chinchang/hint.css#165]
Default display `hint--right`

When hovering over the left edge display `hint--right`

When hovering over the right edge display `hint--left`

When hovering over the top edge display `hint--bottom`

When hovering over the bottom edge display `hint--top`

?

**Comment by chinchang** [comment]
You want to dynamically position the tooltips according to the hover area? That can't be done using just CSS. You'll have to write JavaScript to detect the hover area and then set appropriate `hint-` classe on the element.
