### ISSUE TITLE
set aria-label or data-hint attribute value at runtime

### ISSUE THREAD

**Issue by ajayadglobal360** [chinchang/hint.css#167]
how to set aria-label or data-hint attribute value at runtime

**Comment by chinchang** [comment]
It as simple as setting an attribute on an element. For eg. to set `data-hint` on an element `el` you would do:
```
el.setAttribute('data-hint', 'Tooltip text');
```
Similarly for `aria-label`:
```
el.setAttribute('aria-label', 'Tooltip text');
```

**Comment by janydrozd** [comment]
@ajayadglobal360 is this project still active?

**Comment by chinchang** [comment]
@janydrozd Yes, it is :)
