### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by Observablerxjs** [chinchang/hint.css#169]
I am trying to integrate hint.css to my project however to make the hint to show I have to add 
`@import 'hint.css';` 
to my main styles.css file, is this normal? without this nothing appears when I hover on the element. I added the ` <link rel="stylesheet" href="hint.css">`  in the index.html `HEAD` as written in the Documentation.

**Comment by chinchang** [comment]
`<link rel="stylesheet" href="hint.css">` is enough assuming you have the `hint.css` file along with your html file.

Otherwise, you can `@import 'hint.css'` as well (I am assuming you are using SCSS).
