### ISSUE TITLE
Everything centered

### ISSUE THREAD

**Issue by renatomartins** [chinchang/hint.css#18]
I'd like to center the arrow in the tooltip. Anyone can make this work? I tried playing around with percentages but since the length of the text is dynamic I couldn't manage... Is this possible?
Centering the tooltip would also be nice.
Any ideas?

**Comment by sahat** [comment]
@stevelacey :+1:!

**Comment by chinchang** [comment]
Working on this as part of #94

**Comment by chinchang** [comment]
This is not default behavior of the library since v2.0 :)

**Comment by stevelacey** [comment]
@chinchang now* ?

**Comment by chinchang** [comment]
@stevelacey fixed the typo. Thanks...that was a dangerous one :P

**Comment by stevelacey** [comment]
:smile::ok_hand:
