### ISSUE TITLE
Web Maker Link Broken on the Hint CSS landing page

### ISSUE THREAD

**Issue by sohamsshah** [chinchang/hint.css#188]
How to Reproduce this:
* Go to the Hint.css [landing page](https://kushagra.dev/lab/hint/)
* Click on the Web Maker Toast on the bottom of the Page
* It must redirect to https://webmaker.app/ but it redirects to https://kushagragour.in/lab/web-maker/
* This is probably because of change in website name.

**Comment by divs4799** [comment]
Can I solve this issue? I am an aspiring web developer. @sohamsshah

**Comment by chinchang** [comment]
@divs4799 yes, please go ahead!

**Comment by divs4799** [comment]
@chinchang  where is the Html for landing page? I found demo.html but it looks like it is older version of the landing page.Can you guide me if I am wrong?

**Comment by sohamsshah** [comment]
@divs4799 I suppose this isn't public.

**Comment by divs4799** [comment]
ohkk because i saw only sass and grunt files only one demo.html but it was older version. @sohamsshah

**Comment by chinchang** [comment]
@divs4799  Oh yeah, its a lil messy 😅 sorry about that! The code for this page can be found here - https://github.com/chinchang/kushagra.dev/tree/master/lab/hint

**Comment by divs4799** [comment]
@chinchang  Its all right 😁😁. Thanks for the repository link I will solve the issue in no time.

**Comment by divs4799** [comment]
The issue has been solved Please accept the pull request.

**Comment by chinchang** [comment]
this is fixed now.
