### ISSUE TITLE
NPM installs version with non-MIT license

### ISSUE THREAD

**Issue by ChrisCrossCrash** [chinchang/hint.css#196]
First, thanks a lot for the great library :)

The [npm installable package](https://www.npmjs.com/package/hint.css) is an older version which doesn't have the MIT license. Could you please update the NPM package? I was suprised when I was double-checking my dependencies' licenses in my `node_modules` directory and I noticed that that it had a paid commercial license.

Also, it would be better if there were a `LICENSE` file in the project root with a copy of the MIT license. I've made a PR for this.

**Comment by ChrisCrossCrash** [comment]
Thanks for merging the PR. I just wanted to point out that the NPM-installable version is still a 2 year old version that doesn't include the MIT license. I probably should have split this into two separate issues.

**Comment by chinchang** [comment]
npm package has been updated to 2.7.0. It has a new class too to hide arrow - `hint--no-arrow` :)
Cheers!
