### ISSUE TITLE
Is there a way to add new line in the hint?

### ISSUE THREAD

**Issue by nikolas6** [chinchang/hint.css#24]
The hint looks awesome. I can't seem to find a way or instruction to add new line on the hint. Is there a way to add new line in this version?

Thank you.

**Comment by Romanychev** [comment]
with 1.3.5 version &#10; do not work.
Help me please.

**Comment by Programm3r** [comment]
The following works for me (as stated above)

```
    .hint:after, [data-hint]:after {
        white-space: pre;
    }
```

```
<span class="hint--rounded hint--bounce hint--top" data-hint="line 1 &#10;line 2 &#10;line 3">
       this is some random value
 </span> 
```
