### ISSUE TITLE
z-index as a variable

### ISSUE THREAD

**Issue by jamiebuilds** [chinchang/hint.css#28]
While `1000000` seems like a great number for tooltips, I think it'd be more appropriate in the variables. How about it?

**Comment by tnrich** [comment]
@thejameskyle  @clrunlc and @clrunlc I am hitting the same issue as well. I need the overflow to be hidden, but also need the tooltip to show up... How can I get around this?

**Comment by thejameskyle** [comment]
@tnrich It's just not possible with hint. You can use something like this instead: http://github.hubspot.com/tooltip/docs/welcome/

**Comment by dgodfather** [comment]
For me it was something with my underlying css that I had to work out. I can't quite recall. Do you have a link to your issue?

**Comment by chinchang** [comment]
@tnrich There can only be workarounds for this issue. For example, you could move the tooltip upwards and put it on the element that has `overflow:hidden` on it - if that works for your scenario.

If you could show your exact layout, may be I can suggest something. Otherwise if nothing works, you'll have to use some JavaScript based tooltip like @thejameskyle suggested.

**Comment by tnrich** [comment]
Okay thanks everyone for the input! I'll try using a js solution instead. Can anyone suggest a jquery-free solution that still works in a similar fashion to hintjs's data-attributes?

Thanks!

**Comment by dgodfather** [comment]
@tnrich The thing you should consider is that with a JQuery solution your tooltips can be responsive. I'm not sure about strictly JS and certainly not CSS only.

**Comment by thejameskyle** [comment]
@tnrich The one I mentioned does not have a dependency on jQuery.

@dgodfather There's no reason that jQuery is needed for responsiveness

**Comment by dgodfather** [comment]
Wouldn't JS/Jquery be required to acknowledge window resizing?

**Comment by thejameskyle** [comment]
@dgodfather https://developer.mozilla.org/en-US/docs/Web/Events/resize
