### ISSUE TITLE
Long hints are breaking layout.

### ISSUE THREAD

**Issue by morgoth** [chinchang/hint.css#31]
I tried to prepare some code on CodePen:
http://codepen.io/anon/pen/hoDFb

Sorry for the mess in code.

You can hover over "2NT" on right table to display hint.
As you can see layout is broken, and hint is displayed far after declared content width.

**Comment by acorbi** [comment]
Same happens for me, long hints make the width of my website's container increase. Any possibility to set the tooltip's width and wrap lines?

**Comment by chinchang** [comment]
Yes, sure you can limit width of tooltips. Read here:

https://github.com/chinchang/hint.css/issues/13
https://github.com/chinchang/hint.css/issues/24

**Comment by chinchang** [comment]
Hint.css now has new modifier classes to set tooltip sizes -> hint--small, hint--medium, hint--large
