### ISSUE TITLE
Hints on buttons get stuck in open state after a click

### ISSUE THREAD

**Issue by varemenos** [chinchang/hint.css#63]
Here is an example of what I mean: http://codepen.io/adonisk/pen/eKAIF
You can also see it at http://codemagic.gr , pressing the buttons on the topbar (HTML, CSS, JS, Console etc) will reproduce the issue.

tested it in Chrome v32, Firefox Nightly 28.0a1 and Epiphany (latest)

**Comment by andrewreedy** [comment]
:+1:

**Comment by mazing** [comment]
Why isn't this fixed?

**Comment by chinchang** [comment]
@mazing yes, on focus tooltips are required for accessibility as when someone reaches an element pressing `tab`, he should see tooltip on it.

**Comment by mazing** [comment]
I see :-)

But will the only solution be to tweak the entire code manually, making it, for instance, impossible to load the package through bower etc. if you want the tooltip to hide after clicking a link or button?

**Comment by chinchang** [comment]
I will look into some solution for this. Appreciate any suggestions.

**Comment by mazing** [comment]
Wouldn't it just be to create the same css classes named `hint-hover` without the `:focus` property?

**Comment by stewartcelani** [comment]
@mazing If you still need it I can send you a modified css with the before and after focuses set to hide the arrow and tooltip. =)

**Comment by chinchang** [comment]
This has been fixed in v2.0
