### ISSUE TITLE
Arrow alignment multiline

### ISSUE THREAD

**Issue by sannefoltz** [chinchang/hint.css#69]
With new lines ("\n") and using "white-space:pre-wrap;" on the .hint:after, you can force new lines in tool tips. This all works.

But the arrow on "hint--right" is aligned at the bottom instead of at the top.

Using
.hint--right:before {
  margin-left: -12px;
  margin-top: -6px; }
.hint--right:after {
  margin-top: -14px; }
.hint--right:before, .hint--right:after {
  left: 100%;
  top: 50%; }

fixes it.

**Comment by blainekasten** [comment]
+1, this should be fixed. @chinchang

**Comment by rudza** [comment]
+1
