### ISSUE TITLE
Falls off the edge of the page

### ISSUE THREAD

**Issue by pacanukeha** [chinchang/hint.css#71]
If I have a hint--top or hint--right too close to the right edge or a hint--left too close to the left edge, the tool-tip is drawn outside the window.
I imagine that is tricky to fix without javascript, but it would be nice to have a hint--top and hint--bottom that draws the arrow at the right side of the hint box and has the box extend back to the left instead of out to the right.  Any suggestions?

**Comment by andrewreedy** [comment]
:+1:

**Comment by joaocunha** [comment]
:+1:

**Comment by jonataswalker** [comment]
:+1:

**Comment by chinchang** [comment]
Looking for opinions on the usage of classes for other positions.
Which one would you prefer for a top-left tooltip: `hint--top-left` or `hint--top  hint--left`?

**Comment by quasipickle** [comment]
hint--top hint--left

**Comment by joaocunha** [comment]
:+1: `hint--top` + `hint--left`.

I'd personally prefer `hint--northeast`, but that would require a breaking change for `hint--north` and so on.

**Comment by chinchang** [comment]
this is live with v2.0.0
