### ISSUE TITLE
IE8 transparent background problem

### ISSUE THREAD

**Issue by kebapa** [chinchang/hint.css#84]
IE8 transparent background of hint problem (tooltip show under content)
modification only: white-space: pre-wrap; (because of multilines)

![bug](https://cloud.githubusercontent.com/assets/9686181/5025627/7e889594-6b23-11e4-9c95-89016aa0b29f.png)

**Comment by sureshkumarAQ** [comment]
I would like to work on this task please assign it to me.

**Comment by chinchang** [comment]
closing this as IE8 is an unsupported browser.
