### ISSUE TITLE
Use title attribute if data-hint attribute doesn't exist

### ISSUE THREAD

**Issue by adam-lynch** [chinchang/hint.css#86]

**Comment by chinchang** [comment]
@adam-lynch Seems like to good idea. We just need some way to switch this feature on/off. Thinking loud...SASS variable (custom build) or may be just a line commented in the CSS to turn it on?

**Comment by adam-lynch** [comment]
I don't see why you'd ever want it turned off. 

If you're using it as you are now, then it'll take the `data-hint` value. If you decide to not give a `data-hint` (I assume it does nothing right now), it'll now look for a `title` and use it. If a `title` also doesn't exist, it'll do what it does now when `data-hint` is missing; nothing (same assumption again).

So, disabling it would only make sense for people using this currently without `data-hint` which isn't a use case / doesn't make any sense. Right?

**Comment by dbkaplun** [comment]
+1

**Comment by sasindumendis** [comment]
+1

**Comment by chinchang** [comment]
Was looking into this issue. Some thoughts:

- Right now, the element which should have tooltips are targeted using `[data-hint]` selector. If you provide a fallback to `title` attribute and the element doesn't have a `[data-hint]` attribute, the target selector wouldn't work anymore.

- Having a `title` attribute itself triggers a default tooltip which will conflict with **Hint** tooltips.

**Comment by davidspiess** [comment]
Wouldn't a `title` attribute be better for accessibility too?

**Comment by chinchang** [comment]
In support of accessibility, Hint.css now works with `aria-label` attribute too. As for supporting the `title` attribute, conflict with the native tooltip is an issue which cannot be prevented.
Closing this issue.
