### ISSUE TITLE
Shadow? [Suggestion]

### ISSUE THREAD

**Issue by zztubedogzz** [chinchang/hint.css#87]
I've been playing with your hint.css and found that there is no way to add shadow to the hint without adding a new class... but anyways i made that simple code to add a nice shadow to the hint :)
I would like to ask if this libary is open for ppl to suggest things like this that have chance to get into the product :p 

.hint--shadow:after{
box-shadow:10px 10px 10px #333;
-webkit-box-shadow:10px 10px 10px #333;
-moz-box-shadow:10px 10px 10px #333;
}

**Comment by chinchang** [comment]
Ahh. I found a bug! The shadows should have been present in hint.css. They were to be removed from base file (hint.base.css) but got removed from both. Fixing this.

**Comment by chinchang** [comment]
This is fixed now. You will see shadows if you are using `hint.css`. Thanks for reporting :)

**Comment by zztubedogzz** [comment]
oh well then :) Thanks man :)
Registered just for this tho :p
