### ISSUE TITLE
Font inheritance (icon-font issue)

### ISSUE THREAD

**Issue by joaocunha** [chinchang/hint.css#93]
Our application uses font icons for the tooltips. It obviously inherits from it.

It is possible to fix is on our application level, of course... but I wonder if it's a good idea to prevent this by setting a default `font-family`?

![image](https://cloud.githubusercontent.com/assets/766837/8467438/a1b1efc2-2034-11e5-92ae-6740f462e29b.png)

**Comment by chinchang** [comment]
This is being fixed in !93

**Comment by chinchang** [comment]
this has been fixed in 2.0.0
